db.scraped_html.drop()
db.scraped_html.createIndex({ url: 1 }, { unique: true })
db.scraped_html.createIndex({ tag: 1 })
db.scraped_html.createIndex({ created_at: 1 })
db.scraped_html.createIndex({ updated_at: 1 })